import assert from "node:assert/strict";
import test from "node:test";
import { prependCarrier, stripCarrier, uuidv7, validTraceparent } from "../dist/carrier.js";
import { ChillElectronMain } from "../dist/main.js";
import { ChillElectronRenderer } from "../dist/renderer.js";
import { exposeNamedBridge } from "../dist/preload.js";

const trace = "00-0123456789abcdef0123456789abcdef-0123456789abcdef-01";
const cryptoZero = { getRandomValues: (bytes) => bytes.fill(0) };
const id = uuidv7(0, cryptoZero);
function port(records = []) { return { records, active: "local", record(name, facts) { records.push([name, facts, this.active]); }, withRemoteContext(traceparent, work) { const before = this.active; this.active = traceparent; try { const result = work(); return result?.then ? result.finally(() => { this.active = before; }) : result; } catch (error) { this.active = before; throw error; } }, currentCarrierTraceparent() { return trace; } }; }

test("published package exports only supported entry points", async () => { const manifest = JSON.parse(await (await import("node:fs/promises")).readFile(new URL("../package.json", import.meta.url))); assert.deepEqual(Object.keys(manifest.exports), ["./main", "./renderer", "./preload"]); assert.equal(manifest.version, "0.1.0"); });
test("carrier uses cryptographic bytes, strict trace IDs, and preserves payload identity", () => { const payload = { secret: "privacy-canary" }; const sent = prependCarrier([payload], trace, id); assert.equal(stripCarrier(sent).carrier.messageId, id); assert.strictEqual(stripCarrier(sent).args[0], payload); assert.equal(validTraceparent("00-00000000000000000000000000000000-0123456789abcdef-01"), false); assert.equal(validTraceparent("00-0123456789abcdef0123456789abcdef-0000000000000000-01"), false); assert.equal(validTraceparent("00-0123456789abcdef0123456789abcdef-0123456789abcdef-02"), false); assert.throws(() => prependCarrier([], "00-00000000000000000000000000000000-0123456789abcdef-01", id)); });
test("main joins remote context while async handler and semantic fact share it", async () => { const facts = []; const fake = port(facts); let registered; const main = new ChillElectronMain({ port: fake, now: () => 5 }); main.registerIpc({ handle: (_channel, handler) => { registered = handler; } }, { channel: "raw:private", semanticName: "save_item", handler: async (_event, payload) => { await Promise.resolve(); fake.record("child_span", { outcome: "ok" }); return payload; } }); const payload = { title: "private", url: "https://private", secret: "canary" }; assert.strictEqual(await registered({}, ...prependCarrier([payload], trace, id)), payload); assert.equal(facts[0][2], trace); assert.equal(facts[1][2], trace); assert.equal(facts[1][0], "save_item"); assert.equal(JSON.stringify(facts).includes("private"), false); });
test("renderer creates distinct child carriers with the same trace and preserves payload", async () => { const facts = []; const fake = port(facts); let index = 0; fake.currentCarrierTraceparent = () => `00-0123456789abcdef0123456789abcdef-${index++ ? "2222222222222222" : "1111111111111111"}-01`; const sent = []; const renderer = new ChillElectronRenderer({ invoke: async (_channel, ...args) => { sent.push(args); return args.at(-1); }, send() {} }, { port: fake, browser: { recordStableFact() {} } }); const payload = { error: "privacy-canary" }; assert.strictEqual(await renderer.invoke("save_item", "raw:channel", payload), payload); await renderer.invoke("save_item", "another:raw", payload); const first = stripCarrier(sent[0]).carrier.traceparent; const second = stripCarrier(sent[1]).carrier.traceparent; assert.equal(first.slice(3, 35), second.slice(3, 35)); assert.notEqual(first.slice(36, 52), second.slice(36, 52)); assert.strictEqual(stripCarrier(sent[0]).args[0], payload); });
test("invalid carrier is local and leaves every argument untouched", async () => { const facts = []; const fake = port(facts); let registered; const main = new ChillElectronMain({ port: fake }); main.registerIpc({ handle: (_c, h) => { registered = h; } }, { channel: "raw", semanticName: "semantic", handler: (_e, ...args) => args }); const invalid = { __chill_ipc_v1__: { traceparent: trace, messageId: "not-v7" } }; assert.deepEqual(await registered({}, invalid, "application argument"), [invalid, "application argument"]); assert.equal(facts[0][2], "local"); assert.equal(facts[0][1].correlated, false); });
test("semantic names, durations, errors, and Electron event data stay bounded", async () => { const facts = []; const fake = port(facts); const main = new ChillElectronMain({ port: fake, now: (() => { let value = 0; return () => (value += 100_000); })() }); assert.throws(() => main.registerIpc({ handle() {} }, { channel: "leak:raw", semanticName: "Bad Name", handler() {} })); const listeners = {}; const source = { on: (event, listener) => { listeners[event] = listener; } }; main.observeApp(source); main.observeUpdater(source); listeners["child-process-gone"]({ reason: "privacy-canary", url: "https://private" }); listeners.error(new Error("privacy-canary stack")); assert.equal(JSON.stringify(facts).includes("privacy-canary"), false); const renderer = new ChillElectronRenderer({ invoke: async () => { throw new Error("privacy-canary"); }, send() {} }, { port: fake, browser: { recordStableFact(reason) { facts.push(["browser", { reason }]); } }, now: () => 100_000 }); await assert.rejects(() => renderer.invoke("Bad Name", "raw")); await assert.rejects(() => renderer.invoke("good_name", "raw", { title: "private" })); renderer.recordFailure(); assert.equal(JSON.stringify(facts).includes("private"), false); assert.equal(JSON.stringify(facts).includes("stack"), false); assert.equal(facts.find(([name]) => name === "good_name")[1].duration_ms <= 60_000, true); });
test("preload exposes named functions without generic IPC", () => { let api; exposeNamedBridge({ exposeInMainWorld: (_name, value) => { api = value; } }, "chill", { save: () => 1 }); assert.equal(api.save(), 1); assert.equal("invoke" in api, false); });
