import { type FormEvent, useCallback, useEffect, useState } from "react";
import { ChillApi } from "./api";
import type { AnalyticsWorkspace, ConsoleEnvironment, ConsoleProject, Dashboard, DebuggerSnapshot, QueryResult, SavedQuery } from "./types";

type StudioTab = "live" | "journeys" | "funnels" | "cohorts" | "replay" | "dashboards";
type Visualization = SavedQuery["visualization"];
const tabs: Array<{ id: StudioTab; label: string }> = [
  { id: "live", label: "Live debugger" }, { id: "journeys", label: "Journeys & traces" },
  { id: "funnels", label: "Funnels & paths" }, { id: "cohorts", label: "Cohorts & retention" },
  { id: "replay", label: "Session replay" }, { id: "dashboards", label: "Dashboards & alerts" },
];

export function AnalyticsStudio({ api, project, environment, canRead, canWrite }: { api: ChillApi; project: ConsoleProject; environment: ConsoleEnvironment; canRead: boolean; canWrite: boolean }) {
  const [tab, setTab] = useState<StudioTab>("live");
  const [plan, setPlan] = useState<Record<string, unknown>>(() => planTemplate("events"));
  const [visualization, setVisualization] = useState<Visualization>("table");
  const [result, setResult] = useState<QueryResult | null>(null);
  const [workspace, setWorkspace] = useState<AnalyticsWorkspace | null>(null);
  const [debuggerData, setDebuggerData] = useState<DebuggerSnapshot | null>(null);
  const [error, setError] = useState(""); const [running, setRunning] = useState(false);

  const loadWorkspace = useCallback(async () => { if (!canRead) return; try { setWorkspace(await api.analytics(project.id, environment.id)); } catch (cause) { setError(message(cause)); } }, [api, canRead, environment.id, project.id]);
  useEffect(() => { queueMicrotask(() => void loadWorkspace()); }, [loadWorkspace]);

  useEffect(() => {
    if (tab !== "live" || !canRead) return;
    let active = true; let controller = new AbortController();
    const refresh = async () => {
      try {
        const [debug, events] = await Promise.all([api.debugger(project.id, environment.id, controller.signal), api.query(project.id, environment.id, planTemplate("events"))]);
        if (active) { setDebuggerData(debug); setResult(events); setError(""); }
      } catch (cause) { if (active && !(cause instanceof DOMException && cause.name === "AbortError")) setError(message(cause)); }
    };
    void refresh(); const timer = window.setInterval(() => { controller.abort(); controller = new AbortController(); void refresh(); }, 4_000);
    return () => { active = false; controller.abort(); window.clearInterval(timer); };
  }, [api, canRead, environment.id, project.id, tab]);

  const execute = async (nextPlan = plan, nextVisualization = visualization) => {
    setPlan(nextPlan); setVisualization(nextVisualization); setRunning(true); setError("");
    try { setResult(await api.query(project.id, environment.id, nextPlan)); } catch (cause) { setResult(null); setError(message(cause)); } finally { setRunning(false); }
  };
  const openTrace = (traceId: string) => { const next = planTemplate("trace", { traceId }); setTab("journeys"); void execute(next, "table"); };
  const openReplay = (sessionId: string) => { const next = planTemplate("replay", { sessionId }); setTab("replay"); void execute(next, "table"); };

  return <div className="page analytics-page">
    <header className="analytics-heading"><div><span className="eyebrow">Behavior intelligence</span><h1>Understand what happened, then why.</h1><p>Live behavior, distributed traces, reproducible analysis, and source-masked replay stay synchronized in one tenant-safe workspace.</p></div><div className="freshness-card"><span className="live-pulse" /> <strong>{tab === "live" ? "Live · 4s" : "Manifest-backed"}</strong><span>{environment.name}</span></div></header>
    <nav className="studio-tabs" aria-label="Analytics tools">{tabs.map((item) => <button type="button" key={item.id} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)}>{item.label}</button>)}</nav>
    {!canRead && <div className="analytics-callout">Your role needs <code>data:read</code> to use analytics.</div>}
    {error && <div className="notice error analytics-error"><span>!</span><span>{error}</span></div>}
    {tab === "live" && <LiveDebugger result={result} snapshot={debuggerData} onTrace={openTrace} onReplay={openReplay} />}
    {tab === "journeys" && <JourneyBuilder running={running} result={result} execute={execute} onTrace={openTrace} onReplay={openReplay} />}
    {tab === "funnels" && <FunnelBuilder running={running} result={result} execute={execute} onTrace={openTrace} onReplay={openReplay} />}
    {tab === "cohorts" && <CohortBuilder running={running} result={result} execute={execute} />}
    {tab === "replay" && <ReplayBuilder running={running} result={result} execute={execute} />}
    {tab === "dashboards" && <WorkspacePanel api={api} project={project} environment={environment} workspace={workspace} currentPlan={plan} visualization={visualization} result={result} canWrite={canWrite} reload={loadWorkspace} execute={execute} />}
  </div>;
}

function LiveDebugger({ result, snapshot, onTrace, onReplay }: { result: QueryResult | null; snapshot: DebuggerSnapshot | null; onTrace: (id: string) => void; onReplay: (id: string) => void }) {
  const records = rowsAsObjects(result);
  return <div className="analytics-grid live-grid"><section className="analytics-surface live-feed"><div className="surface-heading"><div><span className="eyebrow">Recent stream</span><h2>Behavior timeline</h2></div><span className="result-count">{records.length} records</span></div>
    <div className="telemetry-list">{records.length ? records.map((record, index) => <TelemetryRecord key={String(record.record_id ?? index)} record={record} onTrace={onTrace} onReplay={onReplay} />) : <AnalyticsEmpty title="Waiting for telemetry" detail="Send an event from an SDK and it will appear here automatically." />}</div></section>
    <aside className="analytics-rail"><section className="analytics-surface"><div className="surface-heading"><div><span className="eyebrow">SDK health</span><h2>Sources</h2></div></div><div className="health-list">{snapshot?.sources.map((source) => <div key={source.data_source_id}><span className={`health-dot ${source.source_status}`} /><div><strong>{source.source_name}</strong><span>{source.source_kind} · {source.active_keys} active key{source.active_keys === 1 ? "" : "s"}</span></div><time>{relativeTime(source.last_used_at)}</time></div>) ?? <span className="subtle">Loading…</span>}</div></section>
      <section className="analytics-surface"><div className="surface-heading"><div><span className="eyebrow">Ingest pipeline</span><h2>Requests & rejections</h2></div></div><div className="request-list">{snapshot?.requests.slice(0, 12).map((request) => <details key={request.id}><summary><span className={`pipeline-state ${request.status}`} /> <strong>{request.signal_kind}</strong><span>{request.record_count} records</span><time>{relativeTime(request.received_at)}</time></summary><dl><div><dt>Request</dt><dd>{request.request_id}</dd></div><div><dt>Format</dt><dd>{request.payload_format}</dd></div><div><dt>Attempts</dt><dd>{request.attempt_count}</dd></div>{request.error_code && <div><dt>Rejected</dt><dd>{request.error_code}: {request.error_message}</dd></div>}</dl><pre>{JSON.stringify(request.metadata, null, 2)}</pre></details>) ?? <span className="subtle">Loading…</span>}</div></section></aside></div>;
}

function JourneyBuilder({ running, result, execute, onTrace, onReplay }: BuilderProps & { onTrace: (id: string) => void; onReplay: (id: string) => void }) {
  const [mode, setMode] = useState<"session" | "trace">("session"); const [identifier, setIdentifier] = useState("");
  const submit = (event: FormEvent) => { event.preventDefault(); void execute(mode === "trace" ? planTemplate("trace", { traceId: identifier }) : planTemplate("events", { sessionId: identifier }), "table"); };
  return <BuilderLayout title="Follow a symptom across UI and services" detail="A session timeline preserves page ancestry and links every traced action to its distributed work." controls={<form className="inline-builder" onSubmit={submit}><select value={mode} onChange={(event) => setMode(event.target.value as "session" | "trace")}><option value="session">Session ID</option><option value="trace">Trace ID</option></select><input value={identifier} onChange={(event) => setIdentifier(event.target.value.trim())} placeholder={mode === "trace" ? "32-character trace ID" : "Session ID"} required /><button type="submit" disabled={running}>{running ? "Tracing…" : "Explore"}</button></form>}>
    <ResultMeta result={result} /><div className="journey-timeline">{rowsAsObjects(result).map((record, index) => <TelemetryRecord key={index} record={record} onTrace={onTrace} onReplay={onReplay} expanded />)}</div>{result && result.rows.length === 0 && <AnalyticsEmpty title="No journey found" detail="Check the identifier and selected environment." />}
  </BuilderLayout>;
}

function FunnelBuilder({ running, result, execute, onTrace, onReplay }: BuilderProps & { onTrace: (id: string) => void; onReplay: (id: string) => void }) {
  const [analysis, setAnalysis] = useState<"funnel" | "path">("funnel"); const [steps, setSteps] = useState("page.viewed, checkout.started, purchase.completed"); const [mode, setMode] = useState("ordered"); const [windowMinutes, setWindowMinutes] = useState(60); const [breakdown, setBreakdown] = useState("none"); const [exclusion, setExclusion] = useState(""); const [propertyKey, setPropertyKey] = useState(""); const [propertyValue, setPropertyValue] = useState(""); const [anchor, setAnchor] = useState("checkout.started"); const [direction, setDirection] = useState("after");
  const run = (event: FormEvent) => { event.preventDefault(); if (analysis === "path") void execute(planTemplate("path", { anchor, direction }), "path"); else { const names = steps.split(",").map((item) => item.trim()).filter(Boolean).slice(0, 8); void execute(planTemplate("funnel", { names, mode, windowMinutes, breakdown, exclusion, propertyKey, propertyValue }), "funnel"); } };
  return <BuilderLayout title="Find conversion and the paths around it" detail="Ordered or unordered funnels and path transitions are compiled by Rust against one immutable manifest." controls={<form className="builder-form" onSubmit={run}><div className="segmented"><button type="button" className={analysis === "funnel" ? "active" : ""} onClick={() => setAnalysis("funnel")}>Funnel</button><button type="button" className={analysis === "path" ? "active" : ""} onClick={() => setAnalysis("path")}>Path discovery</button></div>{analysis === "funnel" ? <><label><span>Semantic steps · comma separated</span><input value={steps} onChange={(event) => setSteps(event.target.value)} /></label><div className="field-row"><label><span>Semantics</span><select value={mode} onChange={(event) => setMode(event.target.value)}><option value="ordered">Ordered</option><option value="unordered">Unordered</option></select></label><label><span>Break down first step</span><select value={breakdown} onChange={(event) => setBreakdown(event.target.value)}><option value="none">No breakdown</option><option value="platform">Platform</option><option value="page">Page</option><option value="kind">Behavior kind</option><option value="name">Event name</option></select></label></div><div className="field-row"><label><span>Conversion window</span><div className="input-unit"><input type="number" min={1} max={44640} value={windowMinutes} onChange={(event) => setWindowMinutes(Number(event.target.value))} /><span>min</span></div></label><label><span>Exclude subjects who did</span><input value={exclusion} onChange={(event) => setExclusion(event.target.value.trim())} placeholder="subscription.cancelled" /></label></div><div className="field-row"><label><span>Annotation property</span><input value={propertyKey} onChange={(event) => setPropertyKey(event.target.value.trim())} placeholder="account.tier" /></label><label><span>Exact value</span><input value={propertyValue} onChange={(event) => setPropertyValue(event.target.value)} placeholder="internal" /></label></div></> : <div className="field-row"><label><span>Anchor event</span><input value={anchor} onChange={(event) => setAnchor(event.target.value)} /></label><label><span>Direction</span><select value={direction} onChange={(event) => setDirection(event.target.value)}><option value="after">What happens after</option><option value="before">What happens before</option></select></label></div>}<button className="run-analysis" type="submit" disabled={running}>{running ? "Calculating…" : "Run analysis"}</button></form>}>
    <ResultMeta result={result} />{analysis === "funnel" ? <FunnelChart result={result} onTrace={onTrace} onReplay={onReplay} /> : <PathChart result={result} onTrace={onTrace} />}
  </BuilderLayout>;
}

function CohortBuilder({ running, result, execute }: BuilderProps) {
  const [analysis, setAnalysis] = useState<"cohort" | "retention">("retention"); const [predicate, setPredicate] = useState<"frequency" | "sequence">("frequency"); const [start, setStart] = useState("session.started"); const [returnEvent, setReturnEvent] = useState("app.opened"); const [minimum, setMinimum] = useState(2); const [sequence, setSequence] = useState("trial.started, feature.used, subscription.started"); const [windowMinutes, setWindowMinutes] = useState(1440); const [propertyKey, setPropertyKey] = useState(""); const [propertyValue, setPropertyValue] = useState("");
  const run = (event: FormEvent) => { event.preventDefault(); const sequenceNames = sequence.split(",").map((item) => item.trim()).filter(Boolean).slice(0, 8); void execute(analysis === "retention" ? planTemplate("retention", { start, returnEvent }) : planTemplate("cohort", { name: returnEvent, minimum, sequence: predicate === "sequence" ? sequenceNames : [], windowMinutes, propertyKey, propertyValue }), analysis === "retention" ? "retention" : "table"); };
  return <BuilderLayout title="Define behavior once, reuse the audience" detail="Event, property, sequence, frequency, and time-window predicates explain individual membership; retention measures recurrence." controls={<form className="builder-form" onSubmit={run}><div className="segmented"><button type="button" className={analysis === "retention" ? "active" : ""} onClick={() => setAnalysis("retention")}>Retention</button><button type="button" className={analysis === "cohort" ? "active" : ""} onClick={() => setAnalysis("cohort")}>Behavioral cohort</button></div>{analysis === "retention" && <label><span>Cohort-forming event</span><input value={start} onChange={(event) => setStart(event.target.value)} /></label>}{analysis === "cohort" && <div className="segmented"><button type="button" className={predicate === "frequency" ? "active" : ""} onClick={() => setPredicate("frequency")}>Frequency</button><button type="button" className={predicate === "sequence" ? "active" : ""} onClick={() => setPredicate("sequence")}>Sequence</button></div>}<label><span>{analysis === "retention" ? "Return event" : predicate === "sequence" ? "Ordered events · comma separated" : "Matching event"}</span><input value={analysis === "cohort" && predicate === "sequence" ? sequence : returnEvent} onChange={(event) => analysis === "cohort" && predicate === "sequence" ? setSequence(event.target.value) : setReturnEvent(event.target.value)} /></label>{analysis === "cohort" && predicate === "frequency" && <label><span>Minimum occurrences</span><input type="number" min={1} value={minimum} onChange={(event) => setMinimum(Number(event.target.value))} /></label>}{analysis === "cohort" && predicate === "sequence" && <label><span>Sequence window</span><div className="input-unit"><input type="number" min={1} max={44640} value={windowMinutes} onChange={(event) => setWindowMinutes(Number(event.target.value))} /><span>min</span></div></label>}{analysis === "cohort" && <div className="field-row"><label><span>Annotation property</span><input value={propertyKey} onChange={(event) => setPropertyKey(event.target.value.trim())} placeholder="account.tier" /></label><label><span>Exact value</span><input value={propertyValue} onChange={(event) => setPropertyValue(event.target.value)} placeholder="enterprise" /></label></div>}<button className="run-analysis" type="submit" disabled={running}>{running ? "Calculating…" : "Run analysis"}</button></form>}>
    <ResultMeta result={result} />{analysis === "retention" ? <RetentionMatrix result={result} /> : <DataTable result={result} />}
  </BuilderLayout>;
}

function ReplayBuilder({ running, result, execute }: BuilderProps) {
  const [identifier, setIdentifier] = useState(""); const [kind, setKind] = useState<"session" | "replay">("session"); const [cursor, setCursor] = useState(0); const records = rowsAsObjects(result); const selected = records[cursor];
  const run = (event: FormEvent) => { event.preventDefault(); setCursor(0); void execute(planTemplate("replay", kind === "session" ? { sessionId: identifier } : { replayId: identifier }), "table"); };
  return <BuilderLayout title="Replay structure without exposing content" detail="Gestures, navigation, behavior, and trace markers share one monotonic timeline. Gaps stay explicit." controls={<form className="inline-builder" onSubmit={run}><select value={kind} onChange={(event) => setKind(event.target.value as "session" | "replay")}><option value="session">Session ID</option><option value="replay">Replay ID</option></select><input value={identifier} onChange={(event) => setIdentifier(event.target.value.trim())} placeholder="Paste identifier" required /><button type="submit" disabled={running}>{running ? "Loading…" : "Load replay"}</button></form>}>
    <ResultMeta result={result} /><div className="replay-player"><div className="replay-stage"><div className="device-frame"><div className="device-status"><span>source masked</span><span>•••</span></div><StructuralFrame record={selected} /></div></div><aside><h3>Timeline</h3><input aria-label="Replay position" type="range" min={0} max={Math.max(0, records.length - 1)} value={Math.min(cursor, Math.max(0, records.length - 1))} onChange={(event) => setCursor(Number(event.target.value))} /><div className="replay-markers">{records.map((record, index) => <button type="button" className={cursor === index ? "active" : ""} key={index} onClick={() => setCursor(index)}><span>{index + 1}</span><div><strong>{replayType(record)}</strong><small>{formatNano(record.effective_occurred_at_unix_nano)}</small></div></button>)}</div></aside></div>
  </BuilderLayout>;
}

function WorkspacePanel({ api, project, environment, workspace, currentPlan, visualization, result, canWrite, reload, execute }: { api: ChillApi; project: ConsoleProject; environment: ConsoleEnvironment; workspace: AnalyticsWorkspace | null; currentPlan: Record<string, unknown>; visualization: Visualization; result: QueryResult | null; canWrite: boolean; reload: () => Promise<void>; execute: (plan: Record<string, unknown>, visualization: Visualization) => Promise<void> }) {
  const [queryName, setQueryName] = useState(""); const [dashboardName, setDashboardName] = useState(""); const [alertName, setAlertName] = useState(""); const [selectedQuery, setSelectedQuery] = useState(""); const [busy, setBusy] = useState(false);
  const mutate = async (operation: () => Promise<unknown>) => { setBusy(true); try { await operation(); await reload(); } finally { setBusy(false); } };
  const saveQuery = (event: FormEvent) => { event.preventDefault(); void mutate(async () => { const saved = await api.createSavedQuery({ project_id: project.id, environment_id: environment.id, name: queryName, description: "Saved from Analytics Studio", plan: currentPlan, visualization }); setSelectedQuery(saved.id); setQueryName(""); }); };
  const createDashboard = (event: FormEvent) => { event.preventDefault(); const ids = selectedQuery ? [selectedQuery] : workspace?.saved_queries.slice(0, 4).map((query) => query.id) ?? []; void mutate(() => api.createDashboard({ project_id: project.id, environment_id: environment.id, name: dashboardName, description: "Shared product and reliability signals", sharing: "organization", layout: ids.map((saved_query_id, index) => ({ saved_query_id, width: index === 0 ? 2 : 1 })) }).then(() => setDashboardName(""))); };
  const createAlert = (event: FormEvent) => { event.preventDefault(); if (!selectedQuery) return; void mutate(() => api.createAlert({ project_id: project.id, environment_id: environment.id, saved_query_id: selectedQuery, name: alertName, operator: "gt", threshold: 0, schedule_minutes: 15 }).then(() => setAlertName(""))); };
  return <div className="workspace-grid"><section className="analytics-surface"><div className="surface-heading"><div><span className="eyebrow">Reusable analysis</span><h2>Saved queries</h2></div><span className="result-count">{workspace?.saved_queries.length ?? 0}</span></div><form className="compact-create" onSubmit={saveQuery}><input value={queryName} onChange={(event) => setQueryName(event.target.value)} placeholder="Name the current analysis" required /><button disabled={!canWrite || busy || !result}>Save current</button></form><div className="saved-list">{workspace?.saved_queries.map((query) => <article key={query.id}><div><span className={`viz-badge ${query.visualization}`}>{query.visualization}</span><strong>{query.name}</strong><small>Fresh {relativeTime(query.updated_at)}</small></div><button type="button" onClick={() => void execute(query.plan, query.visualization)}>Open</button></article>) ?? <AnalyticsEmpty title="No saved queries" detail="Run an analysis and save it for the team." />}</div></section>
    <section className="analytics-surface dashboard-surface"><div className="surface-heading"><div><span className="eyebrow">Team monitoring</span><h2>Dashboards</h2></div></div><form className="compact-create" onSubmit={createDashboard}><input value={dashboardName} onChange={(event) => setDashboardName(event.target.value)} placeholder="Dashboard name" required /><button disabled={!canWrite || busy || !(workspace?.saved_queries.length)}>Create</button></form><div className="dashboard-list">{workspace?.dashboards.map((dashboard) => <DashboardPreview key={dashboard.id} api={api} project={project} environment={environment} dashboard={dashboard} queries={workspace.saved_queries} />)}</div>{workspace?.dashboards.length === 0 && <AnalyticsEmpty title="No dashboards" detail="Save a query, then publish a shared monitoring view." />}</section>
    <section className="analytics-surface alert-surface"><div className="surface-heading"><div><span className="eyebrow">Budget-conscious schedules</span><h2>Alerts</h2></div></div><form className="alert-create" onSubmit={createAlert}><select value={selectedQuery} onChange={(event) => setSelectedQuery(event.target.value)} required><option value="">Saved query…</option>{workspace?.saved_queries.map((query) => <option value={query.id} key={query.id}>{query.name}</option>)}</select><input value={alertName} onChange={(event) => setAlertName(event.target.value)} placeholder="Alert name" required /><button disabled={!canWrite || busy}>Every 15 min</button></form><div className="alert-list">{workspace?.alerts.map((alert) => <div key={alert.id}><span className={`health-dot ${alert.last_state ?? "active"}`} /><div><strong>{alert.name}</strong><span>{alert.operator} {alert.threshold} · every {alert.schedule_minutes} min</span></div><time>{alert.last_evaluated_at ? `Checked ${relativeTime(alert.last_evaluated_at)}` : `Due ${relativeTime(alert.next_evaluation_at)}`}</time></div>)}</div></section></div>;
}

function DashboardPreview({ api, project, environment, dashboard, queries }: { api: ChillApi; project: ConsoleProject; environment: ConsoleEnvironment; dashboard: Dashboard; queries: SavedQuery[] }) {
  return <article className="dashboard-preview"><header><div><strong>{dashboard.name}</strong><span>{dashboard.description}</span></div><span>{dashboard.layout.length} panels · {dashboard.sharing} · fresh {relativeTime(dashboard.updated_at)}</span></header><div className="dashboard-panels">{dashboard.layout.slice(0, 6).map((item, index) => { const query = queries.find((candidate) => candidate.id === item.saved_query_id); return query ? <DashboardQueryPanel key={`${item.saved_query_id}-${index}`} api={api} project={project} environment={environment} query={query} wide={item.width === 2} /> : null; })}</div></article>;
}

function DashboardQueryPanel({ api, project, environment, query, wide }: { api: ChillApi; project: ConsoleProject; environment: ConsoleEnvironment; query: SavedQuery; wide: boolean }) {
  const [result, setResult] = useState<QueryResult | null>(null); const [previous, setPrevious] = useState<QueryResult | null>(null); const [error, setError] = useState("");
  useEffect(() => { let active = true; queueMicrotask(() => { if (!active) return; setResult(null); setPrevious(null); setError(""); void Promise.all([api.query(project.id, environment.id, query.plan), api.query(project.id, environment.id, previousPeriod(query.plan))]).then(([current, prior]) => { if (active) { setResult(current); setPrevious(prior); } }, (cause: unknown) => { if (active) setError(message(cause)); }); }); return () => { active = false; }; }, [api, environment.id, project.id, query]);
  return <section className={`dashboard-panel ${wide ? "wide" : ""}`}><header><div><span className={`viz-badge ${query.visualization}`}>{query.visualization}</span><strong>{query.name}</strong></div><small>{result ? `${result.stats.row_count} rows · ${formatBytes(result.stats.scan_bytes)} · ${comparison(result, previous)}` : error || "Refreshing…"}</small></header>{query.visualization === "funnel" ? <FunnelChart result={result} /> : query.visualization === "path" ? <PathChart result={result} /> : query.visualization === "retention" ? <RetentionMatrix result={result} /> : query.visualization === "line" || query.visualization === "bar" ? <SeriesChart result={result} line={query.visualization === "line"} /> : <DataTable result={result} />}</section>;
}

type BuilderProps = { running: boolean; result: QueryResult | null; execute: (plan: Record<string, unknown>, visualization: Visualization) => Promise<void> };
function BuilderLayout({ title, detail, controls, children }: { title: string; detail: string; controls: React.ReactNode; children: React.ReactNode }) { return <div className="builder-layout"><aside className="analytics-surface builder-sidebar"><span className="eyebrow">Query builder</span><h2>{title}</h2><p>{detail}</p>{controls}</aside><section className="analytics-surface analysis-result">{children}</section></div>; }
function ResultMeta({ result }: { result: QueryResult | null }) { return <div className="result-meta"><div><span className="eyebrow">Result</span><h2>{result ? `${result.stats.row_count} rows` : "Ready to analyze"}</h2></div>{result && <div><span>{formatBytes(result.stats.scan_bytes)} scanned</span><span>{formatDuration(result.stats.total_duration_nano)}</span>{result.stats.cache_hit && <span>cache hit</span>}</div>}</div>; }

function TelemetryRecord({ record, onTrace, onReplay, expanded = false }: { record: Record<string, unknown>; onTrace: (id: string) => void; onReplay: (id: string) => void; expanded?: boolean }) {
  const envelope = parseEnvelope(record.canonical_json); const kind = String(record.kind ?? envelope.kind ?? record.envelope_kind ?? "record"); const name = String(record.name ?? envelope.name ?? kind); const trace = String(record.trace_id ?? envelope.trace?.trace_id ?? ""); const session = String(record.session_id ?? envelope.context?.session_id ?? ""); const page = envelope.context?.page?.path;
  return <details className={`telemetry-record kind-${kind}`} open={expanded}><summary><span className="record-glyph">{glyph(kind)}</span><div><strong>{name}</strong><span>{kind} · {String(record.operation ?? envelope.operation ?? "instant")}{Array.isArray(page) ? ` · ${page.join(" / ")}` : ""}</span></div><time>{formatNano(record.effective_occurred_at_unix_nano)}</time></summary><div className="record-detail"><div className="context-chips">{Object.entries(envelope.annotations ?? {}).slice(0, 8).map(([key, value]) => <span key={key}>{key}: {String(value)}</span>)}</div><pre>{JSON.stringify(envelope, null, 2)}</pre><div className="record-actions">{trace && <button type="button" onClick={() => onTrace(trace)}>Open distributed trace</button>}{session && <button type="button" onClick={() => onReplay(session)}>Open session replay</button>}</div></div></details>;
}
function FunnelChart({ result, onTrace, onReplay }: { result: QueryResult | null; onTrace?: (id: string) => void; onReplay?: (id: string) => void }) { const rows = rowsAsObjects(result); const first = Number(rows[0]?.subjects ?? 0); return <div className="funnel-chart">{rows.length ? rows.map((row, index) => { const count = Number(row.subjects ?? 0); const percent = first ? count / first * 100 : 0; return <div key={index}><div><span>{String(row.step_index ?? index + 1)}</span><strong>{String(row.step_label)}{row.breakdown_value && row.breakdown_value !== "all" ? ` · ${String(row.breakdown_value)}` : ""}</strong><small>{count.toLocaleString()} subjects · {percent.toFixed(1)}%{onTrace && Boolean(row.example_trace_id) && <button type="button" onClick={() => onTrace(String(row.example_trace_id))}>representative trace</button>}{onReplay && Boolean(row.example_session_id) && <button type="button" onClick={() => onReplay(String(row.example_session_id))}>representative replay</button>}</small></div><i style={{ width: `${Math.max(4, percent)}%` }} /></div>; }) : <AnalyticsEmpty title="Define a funnel" detail="Results show conversion and drop-off at every step." />}</div>; }
function PathChart({ result, onTrace }: { result: QueryResult | null; onTrace?: (id: string) => void }) { const rows = rowsAsObjects(result); return <div className="path-chart">{rows.map((row, index) => <article key={index}><span>{String(row.from_name)}</span><i><b>{String(row.sessions)}</b> sessions →</i><span>{String(row.to_name)}</span>{onTrace && Boolean(row.example_trace_id) && <button type="button" onClick={() => onTrace(String(row.example_trace_id))}>trace</button>}</article>)}{!rows.length && <AnalyticsEmpty title="Discover a path" detail="Anchor on a semantic event to reveal neighboring behavior." />}</div>; }
function SeriesChart({ result, line }: { result: QueryResult | null; line: boolean }) { const rows = result?.rows ?? []; const values = rows.map((row) => [...row].reverse().find((value) => typeof value === "number")).map(Number); const maximum = Math.max(1, ...values); return values.length ? <div className={`series-chart ${line ? "line" : "bar"}`}>{values.slice(0, 32).map((value, index) => <i key={index} title={String(value)} style={{ height: `${Math.max(3, value / maximum * 100)}%` }} />)}</div> : <AnalyticsEmpty title="No series yet" detail="This panel refreshes from its saved query." />; }
function RetentionMatrix({ result }: { result: QueryResult | null }) { const rows = rowsAsObjects(result); const periods = [...new Set(rows.map((row) => Number(row.period)))].sort((a, b) => a - b); const cohorts = [...new Set(rows.map((row) => String(row.cohort_bucket)))]; return rows.length ? <div className="retention-wrap"><table className="retention-table"><thead><tr><th>Cohort</th><th>Size</th>{periods.map((period) => <th key={period}>P{period}</th>)}</tr></thead><tbody>{cohorts.map((cohort) => { const cohortRows = rows.filter((row) => String(row.cohort_bucket) === cohort); return <tr key={cohort}><th>{cohort}</th><td>{String(cohortRows[0]?.cohort_subjects ?? 0)}</td>{periods.map((period) => { const value = Number(cohortRows.find((row) => Number(row.period) === period)?.retention_rate ?? 0); return <td key={period}><span style={{ opacity: .18 + value * .82 }}>{(value * 100).toFixed(1)}%</span></td>; })}</tr>; })}</tbody></table></div> : <AnalyticsEmpty title="Calculate retention" detail="Choose cohort-forming and return events to build the matrix." />; }
function DataTable({ result }: { result: QueryResult | null }) { if (!result?.rows.length) return <AnalyticsEmpty title="No result yet" detail="Configure and run the analysis." />; return <div className="analytics-table-wrap"><table className="data-table"><thead><tr>{result.columns.map((column) => <th key={column}>{column.replaceAll("_", " ")}</th>)}</tr></thead><tbody>{result.rows.map((row, index) => <tr key={index}>{row.map((value, cell) => <td key={cell}>{formatCell(value)}</td>)}</tr>)}</tbody></table></div>; }
function StructuralFrame({ record }: { record?: Record<string, unknown> }) { if (!record) return <div className="replay-empty"><span>◌</span><strong>No replay loaded</strong><small>Structure will appear here without text or pixels.</small></div>; const envelope = parseEnvelope(record.canonical_json); const payload = envelope.payload ?? envelope; return <div className="structural-frame"><span className="mask-banner">Masking: {String(envelope.privacy?.redaction_state ?? "source")}</span><div className="structural-nav" /><div className="structural-block wide" /><div className="structural-row"><div className="structural-block" /><div className="structural-block" /></div><div className="structural-list">{[1,2,3,4].map((item) => <i key={item} />)}</div><pre>{JSON.stringify(payload, null, 2).slice(0, 600)}</pre></div>; }
function AnalyticsEmpty({ title, detail }: { title: string; detail: string }) { return <div className="analytics-empty"><span>⌁</span><strong>{title}</strong><p>{detail}</p></div>; }

function planTemplate(kind: string, values: Record<string, unknown> = {}): Record<string, unknown> {
  const end = Date.now() * 1_000_000; const range = { start_unix_nano: end - 7 * 86_400_000_000_000, end_unix_nano: end }; const filter = { behavior_kind: "", operation: "", name: "", annotations: {} }; const base: Record<string, unknown> = { version: 1, kind, range };
  if (kind === "events") base.events = { filter, session_id: values.sessionId ?? "", trace_id: "", installation_id: "", before: null, limit: 500 };
  if (kind === "trace") base.trace = { trace_id: values.traceId ?? "4bf92f3577b34da6a3ce929d0e0e4736", limit: 500 };
  if (kind === "replay") base.replay = { replay_id: values.replayId ?? "", session_id: values.sessionId ?? "", limit: 1000 };
  if (kind === "funnel") { const names = values.names as string[] | undefined ?? ["page.viewed", "purchase.completed"]; const annotations = values.propertyKey && values.propertyValue ? { [String(values.propertyKey)]: String(values.propertyValue) } : {}; base.funnel = { mode: values.mode ?? "ordered", breakdown: values.breakdown ?? "none", exclusions: values.exclusion ? [{ label: "excluded", kind: "", operation: "", name: values.exclusion, annotations: {} }] : [], steps: names.map((name) => ({ label: name.replaceAll(".", " "), kind: "", operation: "", name, annotations })), completion_window_nano: Number(values.windowMinutes ?? 60) * 60_000_000_000 }; }
  if (kind === "path") base.path = { anchor_name: values.anchor ?? "checkout.started", direction: values.direction ?? "after", depth: 3, filter, limit: 250 };
  if (kind === "cohort") { const sequence = values.sequence as string[] | undefined ?? []; const annotations = values.propertyKey && values.propertyValue ? { [String(values.propertyKey)]: String(values.propertyValue) } : {}; base.cohort = { filter: { ...filter, name: values.name ?? "app.opened", annotations }, minimum_count: values.minimum ?? 2, sequence: sequence.map((name) => ({ label: name.replaceAll(".", " "), kind: "", operation: "", name, annotations })), sequence_window_nano: sequence.length ? Number(values.windowMinutes ?? 1440) * 60_000_000_000 : 0, limit: 500 }; }
  if (kind === "retention") base.retention = { start_filter: { ...filter, name: values.start ?? "session.started" }, return_filter: { ...filter, name: values.returnEvent ?? "app.opened" }, interval: "day", periods: 30, limit: 1000 };
  return base;
}
function previousPeriod(plan: Record<string, unknown>): Record<string, unknown> { const copy = structuredClone(plan); const range = copy.range as { start_unix_nano?: number; end_unix_nano?: number } | undefined; if (!range?.start_unix_nano || !range.end_unix_nano) return copy; const duration = range.end_unix_nano - range.start_unix_nano; range.start_unix_nano -= duration; range.end_unix_nano -= duration; return copy; }
function comparison(current: QueryResult, previous: QueryResult | null): string { if (!previous) return "comparing…"; const number = (result: QueryResult) => result.rows.flatMap((row) => [...row].reverse()).find((value) => typeof value === "number") as number | undefined; const now = number(current); const prior = number(previous); if (now === undefined || prior === undefined) return "previous period ready"; if (prior === 0) return now === 0 ? "flat vs previous" : "new vs previous"; const change = (now - prior) / Math.abs(prior) * 100; return `${change >= 0 ? "+" : ""}${change.toFixed(1)}% vs previous`; }
function rowsAsObjects(result: QueryResult | null): Array<Record<string, unknown>> { return result?.rows.map((row) => Object.fromEntries(result.columns.map((column, index) => [column, row[index]]))) ?? []; }
type ParsedEnvelope = {
  kind?: unknown;
  name?: unknown;
  operation?: unknown;
  annotations?: Record<string, unknown>;
  trace?: { trace_id?: unknown };
  context?: { session_id?: unknown; page?: { path?: unknown } };
  payload?: Record<string, unknown>;
  privacy?: { redaction_state?: unknown };
};
function parseEnvelope(raw: unknown): ParsedEnvelope { if (typeof raw !== "string") return {}; try { const value: unknown = JSON.parse(raw); return value && typeof value === "object" ? value as ParsedEnvelope : {}; } catch { return {}; } }
function glyph(kind: string): string { return ({ page: "▣", action: "↗", activity: "⌁", event: "•", replay: "◫", "otel.span": "⇢" } as Record<string, string>)[kind] ?? "·"; }
function replayType(record: Record<string, unknown>): string { const value = parseEnvelope(record.canonical_json); return String(value.payload?.type ?? value.payload?.kind ?? "structure"); }
function formatCell(value: unknown): string { return typeof value === "string" ? value : JSON.stringify(value) ?? ""; }
function formatBytes(value: number): string { return value < 1024 ? `${value} B` : value < 1_048_576 ? `${(value / 1024).toFixed(1)} KiB` : `${(value / 1_048_576).toFixed(1)} MiB`; }
function formatDuration(value: number): string { return value < 1_000_000 ? `${Math.round(value / 1_000)} μs` : `${(value / 1_000_000).toFixed(1)} ms`; }
function formatNano(value: unknown): string { const numeric = Number(value); if (!Number.isFinite(numeric)) return "—"; return new Intl.DateTimeFormat(undefined, { hour: "numeric", minute: "2-digit", second: "2-digit" }).format(new Date(numeric / 1_000_000)); }
function relativeTime(value?: string): string { if (!value) return "never"; const delta = Date.now() - new Date(value).valueOf(); if (!Number.isFinite(delta)) return "unknown"; if (Math.abs(delta) < 60_000) return "now"; if (Math.abs(delta) < 3_600_000) return `${Math.round(Math.abs(delta) / 60_000)}m ${delta >= 0 ? "ago" : "from now"}`; return `${Math.round(Math.abs(delta) / 3_600_000)}h ${delta >= 0 ? "ago" : "from now"}`; }
function message(error: unknown): string { return error instanceof Error ? error.message : "The analytics request failed."; }
